// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {engine} from '../models';
import {tasksclient} from '../models';

export function ChooseSoundFile():Promise<string>;

export function EnterOverlay():Promise<void>;

export function ExitOverlay():Promise<void>;

export function GetSettings():Promise<models.Settings>;

export function GetState():Promise<engine.State>;

export function ListTodaySessions():Promise<Array<models.Session>>;

export function Minimise():Promise<void>;

export function Pause():Promise<engine.State>;

export function Quit():Promise<void>;

export function Relabel(arg1:string,arg2:engine.Binding):Promise<models.Session>;

export function Resume():Promise<engine.State>;

export function SaveSettings(arg1:models.Settings):Promise<models.Settings>;

export function SearchTasks(arg1:string):Promise<Array<tasksclient.TaskOption>>;

export function StartBreak():Promise<engine.State>;

export function StartFocus(arg1:engine.Binding):Promise<engine.State>;

export function StartNext(arg1:engine.Binding):Promise<engine.State>;

export function Stop(arg1:string):Promise<engine.State>;
