// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseSoundFile() {
  return window['go']['main']['App']['ChooseSoundFile']();
}

export function EnterOverlay() {
  return window['go']['main']['App']['EnterOverlay']();
}

export function ExitOverlay() {
  return window['go']['main']['App']['ExitOverlay']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ListTodaySessions() {
  return window['go']['main']['App']['ListTodaySessions']();
}

export function Minimise() {
  return window['go']['main']['App']['Minimise']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Relabel(arg1, arg2) {
  return window['go']['main']['App']['Relabel'](arg1, arg2);
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchTasks(arg1) {
  return window['go']['main']['App']['SearchTasks'](arg1);
}

export function StartBreak() {
  return window['go']['main']['App']['StartBreak']();
}

export function StartFocus(arg1) {
  return window['go']['main']['App']['StartFocus'](arg1);
}

export function StartNext(arg1) {
  return window['go']['main']['App']['StartNext'](arg1);
}

export function Stop(arg1) {
  return window['go']['main']['App']['Stop'](arg1);
}
